### PR TITLE
adding baseless threats to our README

### PR DESCRIPTION
**Pull request by braunshedd**

### CODE REVIEW

**Review by Davoy — APPROVED** [review]
solid change

**Review by kmuga001 — CHANGES_REQUESTED** [review]
Please change 'Or else' as it doesn't seem necessary.

**Comment by braunshedd** [comment]
@kmuga001 plz review changes

**Review by Davoy — APPROVED** [review]
nailed it

**Review by kmuga001 — APPROVED** [review]
This looks good now.

**Pull request merged**
